FROM bellsoft/liberica-openjdk-debian:17

# скопировать все файлы из локальной машины в app
COPY backend/build/output-docker/skill-connect.jar /app/

# задать рабоч директорию
WORKDIR /app

ENTRYPOINT ["java", "-jar" ,"skill-connect.jar"]