spring:
  application:
    name: skill-connect

  datasource:
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db_skill_connect_host:5433/db_skill_connect
    username: postgres
    password: 1

  flyway:
    baselineOnMigrate: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  spring.servlet.multipart.max-file-size=10MB
#  spring.servlet.multipart.max-request-size=10MB

